version: "3"

services:
  postgres:
    image: postgres:9.5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  cachet:
    build:
      context: .
      args:
        - cachet_ver=2.4
    ports:
      - 80:8000
      - 443:8001
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - APP_DEBUG=false
      - APP_ENV=production
      - SESSION_DRIVER=apc
    depends_on:
      - postgres
    restart: on-failure
